---
#
# Build a new Linux dev box
#

- hosts: devboxes
  roles:
    - common
  user: ben
  vars:
    main_user: ben
  vars_files:
    - "vars/defaults.yml"

  #tasks:
    #- include: roles/common/tasks/vim.yml
  tasks:
  - include: tasks/rbenv.yml tags=rbenv
  - include: tasks/rails.yml tags=rails
  - include: tasks/postgresql.yml tags=postgres
  - include: tasks/node.yml tags=node
  - include: tasks/dropbox.yml tags=dropbox
  - include: tasks/chrome.yml tags=chrome
  - include: tasks/dotfiles.yml tags=dotfiles
