---
#
# Build a new Linux dev box
#

- hosts: devboxes
  roles:
    - common
  user: ben
  vars:
    main_user: ben
  vars_files:
    - "vars/defaults.yml"

  #tasks:
    #- include: roles/common/tasks/vim.yml
  tasks:
  - include: roles/dev/tasks/rbenv.yml tags=rbenv
  - include: roles/dev/tasks/rails.yml tags=rails
  - include: roles/dev/tasks/postgresql.yml tags=postgres
  - include: roles/dev/tasks/node.yml tags=node
