---
#
# Build a new Linux dev box
#

- hosts: devboxes
  roles:
    - common
  user: ben
  vars:
    main_user: ben
  vars_files:
    - "vars/defaults.yml"

  #tasks:
    #- include: roles/common/tasks/vim.yml
