---
#
# Build a new Linux dev box
#

- hosts: devboxes
  user: ben
  vars:
    main_user: ben
  vars_files:
    - "vars/defaults.yml"

  tasks:
    - include: tasks/system.yml
    - include: tasks/rbenv.yml
    - include: tasks/rails.yml
    - include: tasks/postgresql.yml
