---
#
# Install Developer libraries
#

- name: Install XMl libraries (for Nokogiri etc...)
  apt: pkg=$item state=installed force=yes
  with_items:
    - libxslt-dev
    - libxml2-dev

- name: Install postgresql dev libraries (for pg etc...)
  apt: pkg=$item state=installed force=yes
  with_items:
    - postgresql-server-dev-{{postgres_version}}
