---
#
# Install rbenv for main user
#
- name: Install rbenv dependencies
  apt: pkg=$item state=installed force=yes
  with_items:
    - build-essential
    - zlib1g-dev
    - libssl-dev
    - openssl
    - libreadline-dev
    - sqlite3
    - libsqlite3-dev
    - libxml2-dev
    - curl
    - wget
    - git-core
  sudo: yes

- name: Install rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: Install ruby-build plugin
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Install rbenv-gem-rehash plugin
  git: repo=git://github.com/sstephenson/rbenv-gem-rehash.git dest=~/.rbenv/plugins/rbenv-gem-rehash

- name: Add RBENV_ROOT to profile
  lineinfile:
    dest=~/.profile
    regexp='RBENV_ROOT=~/.rbenv'
    line='export RBENV_ROOT=~/.rbenv'
    state=present

- name: Add rbenv to PATH
  lineinfile:
    dest=~/.profile
    regexp='RBENV_ROOT/bin'
    line='export PATH="$RBENV_ROOT/bin:$PATH"'
    state=present

- name: Add rbenv init to Bash profile
  lineinfile:
    dest=~/.profile
    regexp='rbenv init -'
    line='eval "$(rbenv init -)"'
    state=present

# Might need to reload shell here

- name: Install Ruby $ruby_version
  command: /home/$main_user/.rbenv/bin/rbenv install $ruby_version creates=/home/$main_user/.rbenv/versions/$ruby_version

- name: Change global Ruby version to $ruby_version
  command: /home/$main_user/.rbenv/bin/rbenv global $ruby_version 

- name: Rebuild the shims
  command: /home/$main_user/.rbenv/bin/rbenv rehash

- name: Ensure rubygems is up-to-date
  command: /home/$main_user/.rbenv/shims/gem update --system
