---
#
# Install vim from source
#
- name: Install dependencies
  apt: pkg=hg state=installed force=yes
  sudo: yes

- name: Clone vim repository
  hg: repo=https://vim.googlecode.com/hg/ dest=~/.build/vim

- name: Copy vim env file
  copy: src=files/vim.env dest=~/.build/vim

- name: Make vim
  shell: cd ~/.build/vim && source vim.env && make reconfig 2>&1 |tee ../make-vim.log

- name: Install vim
  shell: cd ~/.build/vim && make install 2>&1 |tee install.log
