---
#
# System related tasks and tools
#

- name: Update APT repositories
  apt: update_cache=yes
  sudo: yes

- name: Install system tools
  apt: pkg=$item state=installed force=yes
  with_items:
    - htop
    - zsh
    - openssh-server
  sudo: yes

- name: Install GNOME vim
  apt: pkg=vim-gnome state=installed force=yes
  sudo: yes
